### ISSUE TITLE
How to ignore directories

### ISSUE THREAD

**Issue by ecker00** [uctakeoff/vscode-counter#1]
How do you make it ignore some directories? Seems like it might be ignoring `node_modules` already, is there a way to control this and add more directories to that ignore list?

**Comment by uctakeoff** [comment]
There are several ways to exclude files and folders.

### Use `VSCodeCounter.exclude`.

You can use [glob syntax](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options) manually here.

### Use `VSCodeCounter.useFilesExclude` and `files.exclude`.
When `useFilesExclude` is set to true, the contents of the settings `files.exclude` are excluded.

### Use `VSCodeCounter.useGitignore` and `.gitignore`.

If `useGitignore` is set to true, it excludes the contents of `.gitignore`.
(However, this is not completely implemented.)

**Comment by ecker00** [comment]
I'm not using this extension right now, but might in the future again.

Do you mean to create a file in the root of the project named `VSCodeCounter.exclude` and list files to ignore there with glob syntax, the same way a `.gitignore` file works? Or are you talking about VS Code settings?

**Comment by uctakeoff** [comment]
It can be set by [VSCode settings](https://code.visualstudio.com/docs/getstarted/settings).

**Comment by ecker00** [comment]
Thanks for the explanation, that sounds good then!
