### ISSUE TITLE
Suggestion: Configure "VSCodeCounter.outputDirectory" to outside of workspace

### ISSUE THREAD

**Issue by doggy8088** [uctakeoff/vscode-counter#101]
By default, the `VSCodeCounter.outputDirectory` is `.VSCodeCounter`. I'd like to have an option that can point `VSCodeCounter.outputDirectory` to outside of workspace.

For example:

If I setup `VSCodeCounter.outputDirectory` to `C:\TEMP\{workspaceName}`, then the output will located at `C:\TEMP\{workspaceName}` folder which `{workspaceName}` is the name of the current workspace.

In case the `workspaceName` might be duplicate, the name might be able to give a hash of the path of the workspace. I don't really mind the path of the directory. All I need is the output result.

**Comment by uctakeoff** [comment]
@doggy8088 
I tried to support it in v.3.5.
Please try it out.
The variable name is `${workspaceName}`.
