### ISSUE TITLE
[VSCodeCounter] Error has occurred. on counting lines in directory.

### ISSUE THREAD

**Issue by chross** [uctakeoff/vscode-counter#11]
Hi!
I'm on Ubuntu Linux  using VS Code 1.40.0 and VSCode Counter 1.2.1.
When I try to count lines in a directory, I get the following error message:
[VSCodeCounter] Error has occurred.

The console log shows the following:
`console.ts:137 [Extension Host] [VSCodeCounter] countLinesInDirectory : /home/chross/Dropbox/Codebase, Project.Sys/ihg
console.ts:137 [Extension Host] [VSCodeCounter] associations : 1[*.xml,xml]
console.ts:137 [Extension Host] [VSCodeCounter] target : 545 files
console.ts:137 [Extension Host] [VSCodeCounter] use gitignore : /home/chross/Dropbox/Codebase, Project.Sys/project_shared/phpword/.gitignore
console.ts:137 [Extension Host] [VSCodeCounter] use gitignore : /home/chross/Dropbox/Codebase, Project.Sys/project_shared/phpword/samples/results/.gitignore
console.ts:137 [Extension Host] [VSCodeCounter] target : 545 files
notificationsAlerts.ts:40 [VSCodeCounter] Error has occurred.
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:580
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
`

Could the dir name be the reason?

**Comment by uctakeoff** [comment]
I'm sorry, that log alone doesn't make it clear.

A new version has been released.
I also modified the log information, so please check if it works properly.

**Comment by chross** [comment]
It's working now. Thank you very much.
