### ISSUE TITLE
no support for windows1252

### ISSUE THREAD

**Issue by APerricone** [uctakeoff/vscode-counter#14]
I tried this extension, and crashes on graceful-fs becasue: The value "windows1252" is invalid for option "encoding"

![image](https://user-images.githubusercontent.com/22457168/69151620-4762e300-0adb-11ea-83fa-e19d8520b568.png)

In settings.json of workspace I have:
```json
{
    "files.encoding": "windows1252"
}
```
It is a VSCode value.

**Comment by uctakeoff** [comment]
A new version (ver.1.3.1) has been released.
Check if it works correctly.

**Comment by APerricone** [comment]
Tested and it works
