### ISSUE TITLE
How to suport .vue file

### ISSUE THREAD

**Issue by will-zhong** [uctakeoff/vscode-counter#16]
Hi，how can I deal with the .vue file?
Can you help me ?

Regards

**Comment by uctakeoff** [comment]
Wasn't it possible to install this [vue extension](https://marketplace.visualstudio.com/items?itemName=jcbuisson.vue)?

**Comment by dermeister0** [comment]
@uctakeoff 
I've installed the Vue extension, but vscode-counter still does not count lines for .vue files.

**Comment by uctakeoff** [comment]
Please try the following;

#### If you are using RemoteDevelopment, try the following

First, launch VSCode on your local.
Then, open the command palette and select VSCodeCounter: Save the collected language configurations.
Then settings.json will store the configuration information collected from the current language extensions .
Connect to the remote (after updating the remote's VSCodecounter) and use it as usual.

#### Check the languages currently available

* Execute `VSCodeCounter: Check Available Language` on the command palette.
* Check whether the language is available in the language.

#### Look at the debug log.

* Open the debug window from [Help]-[Toggle Developper Tools].
* Run the action of the problem and check the log.
