### ISSUE TITLE
想问一下 可以统计vue-cli4项目的代码行数吗？ 我现在统计提示我找不到files

### ISSUE THREAD

**Issue by hugselina2019** [uctakeoff/vscode-counter#19]
![image](https://user-images.githubusercontent.com/20763416/72661490-94006700-3a15-11ea-8bec-db3b443a999d.png)

**Comment by uctakeoff** [comment]
Wasn't it possible to install this [vue extension](https://marketplace.visualstudio.com/items?itemName=jcbuisson.vue)?

In my environment it seems to be working properly.

![2020-01-21](https://user-images.githubusercontent.com/25006799/72774240-2dfe2480-3c4d-11ea-9321-e2ac1aedc7c3.png)
