### ISSUE TITLE
CSV could be more strictly formed

### ISSUE THREAD

**Issue by GregoryToldhurst** [uctakeoff/vscode-counter#25]
My project has a lot of files with commas in the names. 

eg xml files that are used for test cases 
if the test case is "TestStatusForType(1,2,3)" 
then there will be a file "TestStatusForType(1,2,3)_expectedresult.xml"

This causes a problem because the commas are not in synch with the expected output in CSV format

The result would be better if the filename is always wrapped in double quotes for CSV output 
(but possibly you would need to also remove/escape quotes that are embedded in the filename :) )

**Comment by uctakeoff** [comment]
Fixed in ver. 1.3.5. Please try it out.
