### ISSUE TITLE
Adding a "custom" regex to count for

### ISSUE THREAD

**Issue by maxdd** [uctakeoff/vscode-counter#29]
Hello,
great extension.
It would be great as an improvement/added feature if it could be possible to count for a custom text or a regexpr.
Would that be possible? 
The end goal would be to count for called function ecc, that would make the tool even more complete.

**Comment by uctakeoff** [comment]
Actually, this extension does not support very complex rules.
However, you can implement a few custom rules with the following configuration.

 For example, here is an example configuration for JavaScript.

`settings.json`

```
   "VSCodeCounter.languages": {
          :
        "javascript": {
            "aliases": [
                "JavaScript"
            ],
            "filenames": [
                "jakefile"
            ],
            "extensions": [
                ".js",
                ".es6",
                ".mjs",
                ".cjs",
                ".pac"
            ],
            "lineComments": [
                "//"
            ],
            "blockComments": [
                [
                    "/*",
                    "*/"
                ]
            ],
            "blockStrings": []
        },
           :
  },
```

* An object key is an ID unique to the language. Use an appropriate name that does not conflict with any other.
* Set "aliases" to the language name.
* Set the files that match the "filenames" or "extensions" criteria to It determines that this is JavaScript.
* Lines matching the "lineComments" or "blcokComments" criteria are It will be considered a comment.

The new command "Save the collected language configurations" collects information about other language extensions and stores it in a configuration file You can . for your reference.

**Comment by maxdd** [comment]
Does this make sense? I'ts not working though maybe becase c/c++ are overwriting it?

"printf": {
            "aliases": [
                "PRINTF"
            ],
            "filenames": [],
            "extensions": [
                ".c",
                ".cpp"
            ],
            "lineComments": [
                "printf("
            ],
            "blockStrings": []
        },
