### ISSUE TITLE
Auto ignore the .VSCodeCounter directory

### ISSUE THREAD

**Issue by nateonguitar** [uctakeoff/vscode-counter#3]
Hi, I like this extension, it's pretty awesome!

I just have one request, I have to do this:

```
"VSCodeCounter.exclude": [
     // ignore the output directory or it will be counted it on subsequent counts
    ".VSCodeCounter"
]
```

or if I run it again it adds the output files from running this extension to the totals.

**Comment by uctakeoff** [comment]
@nateonguitar 
I pushed a fix with version 1.0.0. Could you test whether it fixes the issue?
