### ISSUE TITLE
Can count selected code instead of the whole file?

### ISSUE THREAD

**Issue by VonSdite** [uctakeoff/vscode-counter#32]
Can count selected code instead of the whole file?

**Comment by VonSdite** [comment]
I fix it by myselfy

**Comment by uctakeoff** [comment]
Unfortunately, I can't do that now.
But it looked easy enough to make, so I gave it a try.

What do you think when you see this? 
How does it feel compared to what you imagined?
(Look closely at the status bar below)

![2020-07-31](https://user-images.githubusercontent.com/25006799/89036290-63f83000-d377-11ea-8680-2718372c59b1.gif)
