### ISSUE TITLE
Is the Rust programming language supported?

### ISSUE THREAD

**Issue by HTG-YT** [uctakeoff/vscode-counter#41]
I tried to count lines in my Rust project. And it just doesn't work. Is the language supported?

**Comment by HTG-YT** [comment]
It looks like it is supported, but for some reason it doesn't work. It only outputs XML files for some reason.

**Comment by HTG-YT** [comment]
Info: VS Code 1.50.1
Extension Version: 2.2.0

**Comment by uctakeoff** [comment]
This extension makes use of other language extensions to do the aggregation.
Do you have the Rust language extension installed?

You can check the supported languages with the "check available languages" command. Please try it.

**Comment by HTG-YT** [comment]
Yes, I do have the Rust extension installed. By running Check available languages, Rust is also included.

**Comment by HTG-YT** [comment]
Yes, I do have the Rust extension installed. By running Check available languages, Rust is also included.

**Comment by uctakeoff** [comment]
Please tell me which Rust language extension you have installed to try it.

**Comment by HTG-YT** [comment]
This one: https://marketplace.visualstudio.com/items?itemName=rust-lang.rust

**Comment by uctakeoff** [comment]
This is done. What's the problem?
Are you in a Remote Development environment?
![image](https://user-images.githubusercontent.com/25006799/97183229-de9ee300-17e0-11eb-8af0-5991a2e56616.png)

**Comment by HTG-YT** [comment]
No. I'm sure I'm not

**Comment by uctakeoff** [comment]
Can you open the Developer Tool and continue?

Help > Toggle Developer Tools and select Console tab.

You may get a detailed message.

**Comment by HTG-YT** [comment]
Hold on, lemme check

**Comment by HTG-YT** [comment]
![image](https://user-images.githubusercontent.com/39023054/97260532-f36a8d80-1857-11eb-9a0b-66931e5da416.png)

**Comment by HTG-YT** [comment]
Yes - I am on Rust nightly, not stable nor beta.

**Comment by HTG-YT** [comment]
![image](https://user-images.githubusercontent.com/39023054/97260727-5b20d880-1858-11eb-90d5-854fb286e9f5.png)

**Comment by uctakeoff** [comment]
There doesn't seem to be any errors on VSCodeCounter.
The previous error message is bothering me, but I am not a Rust user, so I don't know what the error means.

Disabling or uninstalling the Rust extension once might solve the problem. Just an idea.

**Comment by HTG-YT** [comment]
Thank you - by disabling, it works now. I enabled it again and it also worked: 
![image](https://user-images.githubusercontent.com/39023054/98077576-7b314700-1eab-11eb-8374-b042a1b3438d.png)

Sorry - I was having my tests and I can finally reply with an update here. Thank you again!
