### ISSUE TITLE
There was no target file in remote service

### ISSUE THREAD

**Issue by kong13661** [uctakeoff/vscode-counter#43]
I want to count my c++ codes in my remote service, but it said There was no target file. I'm sure I have installed the C/C++ package.

**Comment by uctakeoff** [comment]
When using VSCode Counter in *VSCode Remote Development*, use the `Save language configurations` function You will need to. 
[See below for more information](#save-language-configurations).

**Comment by kong13661** [comment]
> When using VSCode Counter in _VSCode Remote Development_, use the `Save language configurations` function You will need to.
> [See below for more information](#save-language-configurations).

I am sorry for my late response. It works! Thank you!

**Comment by rohitkrishna094** [comment]
@kong13661 https://github.com/uctakeoff/vscode-counter#save-language-configurations

Its the above link.
