### ISSUE TITLE
language based on folder name

### ISSUE THREAD

**Issue by yfengBTI** [uctakeoff/vscode-counter#44]
Is it possible to designate JSON files inside a folder a different language?
I see that filename is an option but not folder name, and I understand there's a directory view below.
This will give me control to create a better summary view up top.

**Comment by uctakeoff** [comment]
I'm sorry. Your English is too difficult for me to understand, I'm not sure I could.
Do you want to aggregate by folder?
I don't think your idea is useful to many other people at the moment.
You can get detailed statistics for each folder from the **result.csv** file.
Isn't it possible to get the information you want by processing the CSV file?

**Comment by uctakeoff** [comment]
Alternatively, you could also add the summary information to the CSV file and output the language distribution of each directory.

**Comment by yfengBTI** [comment]
So let's say I have this folder structure:
```
objects/
├── processes/
│   ├── refresh-dimensions.json
│   ├── reload-data-files.json
│   ├── reload-env-var.json
│   └── reload-feeders.json
├── chores/
│   ├── on-server-startup.json
│   └── hourly.json
```

We use json files to define a lot of different object types, and each type follows a different schema.
It would be nice to be able to see these as `Process-JSON` and `Chore-JSON` instead of only `JSON` because of the schema differences.

Hope that makes sense.

**Comment by uctakeoff** [comment]
Thank you for the detailed explanation. Perhaps that makes sense.
But I still can't generalize your ideas.
And it is difficult to determine automatically when your ideas should be applied.

As an alternative, I suggest you to prepare a table in summary like the following

|dir|JSON|YAML|TypeScript|...|
|:-|-:|-:|-:|-:|
|objects/| 3456|123|5678|...|
|objects/processes| 1222|0|0|...|
|objects/chores| 578|0|0|...|
