### ISSUE TITLE
Simply does not work after v1.3.0!

### ISSUE THREAD

**Issue by philbowles** [uctakeoff/vscode-counter#46]
No matter what I try, be it workspace, directory I get the error: [VSCodeCounter] There was no target file.

Version is showing as 2.2.1 and I'm using the latest fully-up-to-date version of VSCode

I "walked back" the versions... anything below 1.3.1 works , nothing above 1.3.0 works, all failing with the error above

**Comment by uctakeoff** [comment]
Thanks for the report.
* Please let me know which OS you use VSCode on.
* Are you using RemoteDevelopment?
* Do you use any symbolic links?

**Comment by pragmatically-dev** [comment]
Unable to install extension 'uctakeoff.vscode-counter' as it is not compatible with VS Code '1.52.1'.

**Comment by yanyan0207** [comment]
I have found that it does not work if the number of target files is very large.

In my case, it simply does not work when there are 11,670 cpp files. (No output, no error log).

Adding "Exclude" Settings to reduce the number of target files made it work.

**Comment by uctakeoff** [comment]
@yanyan0207 
Probably fixed in ver. 2.3.0. Please try it out.

**Comment by Zielgestalt** [comment]
For me It only works for folders that aren't excluded by .gitignore. Just comment the lines out in gitignore - everything works for me.
v2.3.0, MacOs 11.4.

**Comment by uctakeoff** [comment]
@Zielgestalt 
VS Code Counter references  .gitignore setting.
If you don't need it, disable the "VSCode Counter: Use Gitignore" setting.

**Comment by yanyan0207** [comment]
> @yanyan0207
> Probably fixed in ver. 2.3.0. Please try it out.

It works fine! thanks!
