### ISSUE TITLE
How to exclude some files I want,like .class

### ISSUE THREAD

**Issue by FightingFZC** [uctakeoff/vscode-counter#47]

**Comment by FightingFZC** [comment]
I added .class、*.class、**.class, but it didn't work，
![image](https://user-images.githubusercontent.com/74097223/106009370-35270080-60f3-11eb-8edd-642ef5b02a9e.png)
![image](https://user-images.githubusercontent.com/74097223/106009391-3d7f3b80-60f3-11eb-81f0-0c76ff6accde.png)

**Comment by uctakeoff** [comment]
Try setting it up as follows

`**/*.class`

**Comment by FightingFZC** [comment]
> Try setting it up as follows
> 
> `**/*.class`

Thank you.It worked.
