### ISSUE TITLE
Wrong results when there is a 2nd directory which has the requested name included

### ISSUE THREAD

**Issue by goeppner** [uctakeoff/vscode-counter#48]
When I execute "count lines in directory" on a directory e.g. named "swcMatrix" and there is a 2nd directory which has the same name included, e.g. "swcMatrixLedController", the 2nd directory is counted additionally in the result, here the file result.md:
`# Summary

Date : 2021-02-04 06:31:49

Directory u:\app\swcMatrix

Total : 21 files,  5348 codes, 1184 comments, 1025 blanks, all 7557 lines

[details](details.md)

## Languages
| language | files | code | comment | blank | total |
| :--- | ---: | ---: | ---: | ---: | ---: |
| C | 10 | 4,520 | 966 | 816 | 6,302 |
| C++ | 11 | 828 | 218 | 209 | 1,255 |

## Directories
| path | files | code | comment | blank | total |
| :--- | ---: | ---: | ---: | ---: | ---: |
| . | 21 | 5,348 | 1,184 | 1,025 | 7,557 |
| .. | 15 | 3,924 | 493 | 727 | 5,144 |
| ..\swcMatrixLedController | 15 | 3,924 | 493 | 727 | 5,144 |
| ..\swcMatrixLedController\include | 8 | 741 | 166 | 169 | 1,076 |
| ..\swcMatrixLedController\src | 7 | 3,183 | 327 | 558 | 4,068 |
| include | 3 | 87 | 52 | 40 | 179 |
| src | 3 | 1,337 | 639 | 258 | 2,234 |

[details](details.md)`

VS Code Counter version: v2.2.1
Could this issue please be fixed?

**Comment by uctakeoff** [comment]
Thanks for the report.
Fixed in version 2.2.2.
Please update your VSCode to the latest version and try it.

**Comment by goeppner** [comment]
Great! Issue is fixed and works correctly. Thank you for the quick response!
