### ISSUE TITLE
Error on large code bases

### ISSUE THREAD

**Issue by schallm** [uctakeoff/vscode-counter#5]
I'm receiving the following on workspaces with large numbers of files when running "VSCodeCounter: Count lines in workspace"...

```
<path to file> Read Error : EMFILE: too many open files, open <path to file>
```

I have been able to get around in some projects with excludes, but would be nice to not have to exclude files.

**Comment by uctakeoff** [comment]
I corrected this problem with ver.1.0.1.
Please check if the problem is solved or not.

**Comment by schallm** [comment]
Works great!  Thanks!
