### ISSUE TITLE
Vscode Counterで行数がカウントできません。"The "input" argument must be an instance of ArrayBuffer or ArrayBufferView. Received null"

### ISSUE THREAD

**Issue by oldschooleer** [uctakeoff/vscode-counter#52]
Visual Code Studio version: 1.60.2 (user setup)
VS Code Counter version: V2.3.0

CloneをLocalに作成して、コードのカウントを行おうとしましたが、
ディレクトリ内のコードが数えられません。コードファイルは存在します。
Error MSG="The "input" argument must be an instance of ArrayBuffer or ArrayBufferView. Received null"
何が原因か分かりません。

**Comment by uctakeoff** [comment]
メニューの Help > Toggle Developper Tool で デバッグ出力を見ることができるようになります.
これを表示させた状態で実行して, エラーが発生したときに出力されたメッセージをすべて教えて下さい.

なにか原因がわかるかもしれません.
