### ISSUE TITLE
jupyter output lines are counted

### ISSUE THREAD

**Issue by mind6** [uctakeoff/vscode-counter#54]
Sometimes when you have a large table or graph output, the number of output lines dominates the whole project. Should the notebook outputs be excluded from the count?

**Comment by mind6** [comment]
> I can't judge. It's probably not my problem, but yours. If you find it disturbing, you can eliminate it.
> 
> I'm sorry if I sound cold. I have no idea what "jupyter output" is.

It's referring to the output section of jupyter notebooks. The output can be columns of data generated by your program, or javascript describing the chart. It would be nice to have the option to exclude them. Just wondering if people are considering this feature.

**Comment by uctakeoff** [comment]
The following site describes how to specify data in jupyter notebook that you don't want stored in git.

https://medium.com/@cruble/a-quick-guide-for-making-a-git-ignore-gitignore-e645d70676b2

vscode-counter has a mechanism to exclude the contents of .gitignore from being included.
I'm not sure if this solves your problem.
