### ISSUE TITLE
Counting .h as C++ code

### ISSUE THREAD

**Issue by gabrielbergoc** [uctakeoff/vscode-counter#55]
I worked on a project for a college assignment, it's written entirely in C (and a single python script), and VS Code Counter is considering my C header files (.h) as C++ code:
![image](https://user-images.githubusercontent.com/59211540/143597370-c9d4bb14-60e3-4d23-bd21-3574d1b45675.png)

(I checked the headers' number of lines, they match the C++ column)

**Comment by uctakeoff** [comment]
From version 3.0 onwards, file associations are taken into account.

https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file
