### ISSUE TITLE
Unable to resolve nonexistent file

### ISSUE THREAD

**Issue by John4266** [uctakeoff/vscode-counter#62]
Hello.
When i am trying to use the extension, i encounter the following error message in console and nothing happens:

```
rejected promise not handled within 1 second: EntryNotFound (FileSystemError): Unable to resolve nonexistent file 'd:\Users\Win10\Desktop\Visual Studio\Visual Studio Code\Projects\test-stuff\.VSCodeCounter'

stack trace: EntryNotFound (FileSystemError): Unable to resolve nonexistent file 'd:\Users\Win10\Desktop\Visual Studio\Visual Studio Code\Projects\test-stuff\.VSCodeCounter'
```

Some info:
Operating System: Windows 10 Pro
Architecture: 64 Bit
VSCode Version: 1.63.2 (user setup)
Extension Version: 3.0.0

**Comment by uctakeoff** [comment]
@John4266 
I'm sorry. It was an inadvertent mistake after the update.
It has been fixed in ver. 3.0.1.
