### ISSUE TITLE
[Feature Request] - Add Totals of that bottom of different views for Count Lines in Workspace

### ISSUE THREAD

**Issue by ondrovic** [uctakeoff/vscode-counter#65]
Might be more useful to have the totals at the bottom of the different views instead of the top something like the following
![summary](https://user-images.githubusercontent.com/3682042/156669001-e9e7a48e-89ce-40da-8cd0-473c281be055.png)
![details](https://user-images.githubusercontent.com/3682042/156669002-d0e7f041-b866-4a9a-a613-10eb6a92b77d.png)

**Comment by uctakeoff** [comment]
"." in "Directories" contains the aggregate results of all files in the target directory.
This is effectively the same as "Totals".

And the content of "Totals" does not change whether it is "Directories" or "Lanaguages".
Therefore, I do not see any inconvenience in leaving it as it is now.

For more advanced totals, CSV is recommended.
