### ISSUE TITLE
Asterisk (*) in .gitignore does not work correctly

### ISSUE THREAD

**Issue by Programmierus** [uctakeoff/vscode-counter#68]
I have following entry in my `.gitignore` which is perfectly valid:

```
venv*/
```

Git successfully ignores matching folders, but VS Code Counter still counts them in.

**Comment by uctakeoff** [comment]
Ver. 3.0.4 has been released.
One problem has been corrected.
If this does not fix the problem, please provide more information.

**Comment by Programmierus** [comment]
Works for me, thank you!
