### ISSUE TITLE
Moving extension ".h" from "C++" to "C" in settings.json, it gets put back to "C++" automatically

### ISSUE THREAD

**Issue by bengalack** [uctakeoff/vscode-counter#69]
Using current version in Marketplace. When I move extension ".h" from "C++" to "C" in settings.json, it gets put back to "C++" for no reason. I do not have any C++ in my project, and any .h-file is a C-file to me, and I want it counted as such.

It seems like a bug to me, but maybe I do something wrong?

**Comment by uctakeoff** [comment]
I have never met such a problem.
I do not think it is a problem with VSCodeCounter.
https://code.visualstudio.com/docs/languages/identifiers
