### ISSUE TITLE
Path is rendered incorrectly

### ISSUE THREAD

**Issue by rhys-vdw** [uctakeoff/vscode-counter#74]
![image](https://user-images.githubusercontent.com/822105/170918367-98509807-e81a-4563-b3a6-dc5c723c15c9.png)

Path should be: `C:\Users\rhysv\Projects\enter-the-chronosphere\Assets\_Game\Scripts`

The backslash before `_` is elided. Perhaps the `\` is being treated as an escape?

**Comment by uctakeoff** [comment]
Fixed in version 3.0.5.
