### ISSUE TITLE
How to block Comments？

### ISSUE THREAD

**Issue by 836672549** [uctakeoff/vscode-counter#76]
![image](https://user-images.githubusercontent.com/71533394/176392134-315c5040-91ad-4277-9662-ce80af137f29.png)
My code blockCommentBegins with "/**", and blockCommentEnd with "*/". How to write the format？

**Comment by uctakeoff** [comment]
Set as follows.
```json
        "blockComments": [["{/**", "*/}"]],
```

**Comment by 836672549** [comment]
OK, Thanks.

**Comment by 836672549** [comment]
![image](https://user-images.githubusercontent.com/71533394/177066215-ab0397d1-6d7c-43f6-92d6-ffcfa3a3cd86.png)
How to add the "blockcomment" tag on the diagram？

**Comment by uctakeoff** [comment]
Block comments are included in  "comment".
