### ISSUE TITLE
Support storing collected language elsewhere 

### ISSUE THREAD

**Issue by RichardLuo0** [uctakeoff/vscode-counter#78]
The settings.json becomes extremely long after running `VSCodeCounter: Save the collected language configurations`.  Could you support storing it in for example ~/.vscode-counter-language.json? Or allow us to specify the location?

**Comment by uctakeoff** [comment]
By setting `VSCodeCounter.saveLocation` to `"output directory"`, the destination file can be .VSCodeCounter/languages.json.

**Comment by RichardLuo0** [comment]
I see. Is it possible to store it in a commonplace other than global settings? Because it seems like it can be shared across multiple projects. It's too much trouble to collect configurations for every project.

**Comment by RichardLuo0** [comment]
I understand that I can change the output directory. Just I usually store the output per project. And I am using WSL which makes collecting language mandatory, so I hope there's a setting to store the file in a generic place.

**Comment by uctakeoff** [comment]
The setting `VSCodeCounter.languageConfUri` was added in version 3.1.0.
You can specify any path here.
However, it will not be effective unless you specify `"use languageConfUri"` in `VSCodeCounter.saveLocation`.

**Comment by RichardLuo0** [comment]
Thank you, I will close the issue
