### ISSUE TITLE
Count the files in the top-level as a separate item

### ISSUE THREAD

**Issue by jalil1992** [uctakeoff/vscode-counter#81]
Now the extension counts lines of codes traversing all directories.
And the files in the top level (not necessarily the top level but the direct level files) are not being counted separately and included in the item for the folder.
I hope we could have a separate item for each folder with a special name and show the number of lines in the files that are directly included in that folder.

![screenshot_89](https://user-images.githubusercontent.com/98934018/206706756-7a14b8a1-f070-4242-bf90-2f0e97ee614d.png)

P.S. I am happy to help out if you are busy.

**Comment by uctakeoff** [comment]
Supported in v3.2.0. Please check it.

**Comment by jalil1992** [comment]
I confirm it works as requested. Thank you!
