### ISSUE TITLE
Bug : blockComments character in a line of code falsifies the counts

### ISSUE THREAD

**Issue by jamel-tirari** [uctakeoff/vscode-counter#88]
Hello,

There is a bug in the codes/comments lines counts when the opening characters of a comment block is inside a line of code. Here is an example (in C#, but the bug is in all languages i tested) : 

Normal operation ( without block comment opening characters in a line of code ) :
![image](https://user-images.githubusercontent.com/40656336/235883565-e6b8574c-009f-470b-a645-00e61f5f21ff.png)

Bug :
![image](https://user-images.githubusercontent.com/40656336/235883632-54fd79ac-25db-42ed-a119-fe38d25e3a20.png)

![image](https://user-images.githubusercontent.com/40656336/235883655-33d6444e-be57-4e2f-8e81-1d5fa670e779.png)

Best Regards,

**Comment by uctakeoff** [comment]
Fixed in ver. 3.4.0
