### ISSUE TITLE
Trailing newline ('\n') character in source code is treated as an extra blank line

### ISSUE THREAD

**Issue by markafitzgerald1** [uctakeoff/vscode-counter#96]
It would be helpful to be able to treat a trailing newline ('\n') character as the end of the line immediately preceding it, instead of treating it as a separate blank line at the end of the file as VS Code Counter currently does. Having VS Code Counter do this would match the POSIX interpretation of tools like `wc -l`. Could this possibly be added as an option, or as a change of core tool behaviour?

As a bonus, adding this functionality would also allow output from VS Code Counter to align with that of the fairly popular [cloc](https://github.com/AlDanial/cloc) command line lines of code counting tool.

**Comment by markafitzgerald1** [comment]
P.S. Awesome tool, by the way - thanks for creating and maintaining it! ❤️

**Comment by uctakeoff** [comment]
Incidentally, the current implementation is the same as the VSCode counting method.
![image](https://github.com/uctakeoff/vscode-counter/assets/25006799/7f19d381-fc29-4ec2-ad07-9076e64aa77d)

**Comment by markafitzgerald1** [comment]
Thanks for the response and great question about how `wc` defines lines, @uctakeoff. I believe [POSIX](https://en.wikipedia.org/wiki/POSIX) (Linux and other Unixes) specifies how Unix tools like `wc` define lines of text - specifically [Line](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) and [Incomplete Line](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_195).

In the screenshot you share, I guess that if you're in a file that ends in an [Incomplete Line](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_195) the incomplete line does have a line number, but does not count into the overall line count in POSIX and POSIX tools like `wc`. Thus VS Code shows its line number, even though it is potentially an Incomplete Line.

**Comment by uctakeoff** [comment]
I understood that a line that does not end in a newline is not considered a "line".
This has been addressed in ver. 3.3.0.
However, the default behaviour is the same as before, so please set `includeIncompleteLine` to `false` in the configuration.

**Comment by uctakeoff** [comment]
Oh, I mistakenly set the default setting to false. Oh well.
